//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public System.Guid permissionID { get; set; }
        public System.Guid audioID { get; set; }
        public System.Guid userID { get; set; }
        public byte permission1 { get; set; }
    
        public virtual Audio Audio { get; set; }
        public virtual User User { get; set; }
    }
}
